### ISSUE TITLE
working example

### ISSUE THREAD

**Issue by mitjarobic** [thekonz/apollo-lighthouse-subscription-link#1]
Hello, 

are you willing to provide a demo working example using apollo-lighthouse-subscription-link and lighthouse-redis-broadcaster?

Thank you.

**Comment by thekonz** [comment]
Follow the readme and you got a working example. Should take around 5 minutes.

Is there a concrete issue with this package?

**Comment by mitjarobic** [comment]
I keep getting [ApolloLink is not defined](https://ibb.co/JHN37jy) in js console

**Comment by thekonz** [comment]
I guess, you might need to import ApolloLink aswell.

```js
import ApolloLink from "apollo-link"
```

**Comment by thekonz** [comment]
@mitjarobic is this still an issue for you?

**Comment by mitjarobic** [comment]
Yes. Still an issue when using the package. I solved it by copying your file locally and then import it.

**Comment by thekonz** [comment]
What bundler/setup are you using?

**Comment by thekonz** [comment]
@mitjarobic can you try and upgrade to 1.0.9 and see if that fixes the bug for you?
Thanks

**Comment by mitjarobic** [comment]
Yes, it is fixed. Thanks.
