### ISSUE TITLE
Incompatible with new channel format

### ISSUE THREAD

**Issue by GregPeden** [thekonz/apollo-lighthouse-subscription-link#6]
The new pattern for channels described here is not supported:

https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#use-subscriptions-response-format-version-2

In my experience, in v5.x of Lighthouse, if channel version is set set to "1", it still ALSO includes the version 2 path to the channel. Setting the channels version to 2 in config basically drops the old v1 format. In this way, it's safe within 5.x version to just always check the version 2 path.

**Comment by SirLamer** [comment]
https://github.com/thekonz/apollo-lighthouse-subscription-link/pull/7

**Comment by thekonz** [comment]
#14
